### PR TITLE
Fix postgres don't have permissions to data folder

### PR DESCRIPTION
**Pull request by iSevenDays**
I was getting errors:
initdb: could not access directory "/var/lib/postgresql/data": Permission denied

Environment: mac OS 10.14.6

My pull request fixes the error.

### CODE REVIEW

**Comment by iSevenDays** [comment]
@gfunkmonk I still can't run it locally, did you fix the following issue?
```
web_1       | [25/Sep/2019 16:14:46] ERROR [django.request:114] Internal Server Error: /ide/project/1/autocomplete/init
web_1       | Traceback (most recent call last):
web_1       |   File "/code/utils/jsonview.py", line 54, in _wrapped
web_1       |     ret = f(request, *args, **kwargs)
web_1       |   File "/code/ide/api/ycm.py", line 29, in init_autocomplete
web_1       |     file_contents[f.project_path] = f.get_contents()
web_1       |   File "/code/ide/models/s3file.py", line 68, in get_contents
web_1       |     return s3.read_file(self.bucket_name, self.s3_path)
web_1       |   File "/code/utils/s3.py", line 85, in read_file
web_1       |     bucket = _buckets[bucket_name]
web_1       |   File "/code/utils/s3.py", line 66, in __getitem__
web_1       |     self.configure()
web_1       |   File "/code/utils/s3.py", line 48, in configure
web_1       |     _ensure_bucket_exists(self.s3, settings.AWS_S3_SOURCE_BUCKET)
web_1       |   File "/code/utils/s3.py", line 13, in _ensure_bucket_exists
web_1       |     s3.create_bucket(bucket)
web_1       |   File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 613, in create_bucket
web_1       |     data=data)
web_1       |   File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 665, in make_request
web_1       |     retry_handler=retry_handler
web_1       |   File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
web_1       |     retry_handler=retry_handler)
web_1       |   File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
web_1       |     raise ex
web_1       | error: [Errno 111] Connection refused
```

**Comment by gfunkmonk** [comment]
Kinda. I've fixed that, qemu will bootup and VNC connects but for some reason it hangs on installing the app to it now.

**Comment by iSevenDays** [comment]
@gfunkmonk I have just got the apps running in CloudPebble on mac OS 10.14.6
Please feel free to use my code
https://github.com/iSevenDays/cloudpebble-composed

**Comment by gfunkmonk** [comment]
The emulator works? Mine did, I'm just not sure how I broke it....

**Comment by iSevenDays** [comment]
@gfunkmonk yes, I was able to lunch this example
https://github.com/pebble-examples/ks-clock-face/blob/master/src/ks-clock-face.c

**Pull request merged**
